#!/usr/bin/env ruby 

require 'jboss-cloud-config'

$: << 'lib/jboss-cloud-support/lib'

require 'wizard/app'

trap("INT"){
  exit(0)
}

JBossCloudWizard::App.new(
  :name            => JBossCloudConfig.config.name,
  :version         => JBossCloudConfig.config.version,
  :release         => JBossCloudConfig.config.release,
  :dir_appliances  => "/home/goldmann/jboss-cloud/appliances"
).run
